import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {createShowroom} from './scene.js';
import {PLAN,ZONES,ROUTES,world} from './layout.js';
import {QUALITY} from './visuals.js';
import {DEVICE_ZONE_COPY} from './devices.js';
import {COUNTRY_PRESETS,getCountry} from './country-presets.js';
for(const zone of ZONES)if(DEVICE_ZONE_COPY[zone.id])zone.description=DEVICE_ZONE_COPY[zone.id];

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const canvas=$('#scene'),viewport=$('.viewport'),loading=$('#loading');
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let renderer,model;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(QUALITY.dpr);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.9;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.info.autoReset=false;model=createShowroom(renderer);}catch(e){loading.innerHTML='<strong>暂时无法启动三维视图</strong><span>请使用支持 WebGL 的浏览器，并开启硬件加速。</span>';console.error(e);throw e;}
model.shell.visible=false;
renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;
const camera=new THREE.PerspectiveCamera(43,1,.08,100);camera.position.set(...ZONES[0].camera);
const planCamera=new THREE.OrthographicCamera(-7,7,7,-7,.1,100);planCamera.position.set(0,30,.001);planCamera.up.set(0,0,-1);planCamera.lookAt(0,0,0);
let activeCamera=camera;
const controls=new OrbitControls(camera,canvas);controls.target.set(...ZONES[0].target);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=1.3;controls.maxDistance=30;controls.maxPolarAngle=Math.PI*.493;controls.minPolarAngle=.07;controls.screenSpacePanning=true;controls.update();
const target=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,samples:4});const composer=new EffectComposer(renderer,target);const renderPass=new RenderPass(model.scene,camera);composer.addPass(renderPass);const bloom=new UnrealBloomPass(new THREE.Vector2(800,600),.32,.25,1.15);composer.addPass(bloom);composer.addPass(new OutputPass());
const state={mode:'overview',zone:'all',route:null,stop:0,transition:null,yaw:0,pitch:0,drag:false,keys:new Set(),lastPointer:null,doorPass:true};let toastTimer;
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
let selectedCountry='au';
try{selectedCountry=getCountry(localStorage.getItem('showroom-country')).id;}catch{}
function selectCountry(id,announce=true){const preset=model.setCountry(id);selectedCountry=preset.id;for(const b of $$('[data-country]')){const active=b.dataset.country===selectedCountry;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));}try{localStorage.setItem('showroom-country',selectedCountry);}catch{}renderer.shadowMap.needsUpdate=true;if(announce)toast(`已切换至${preset.label}：室内乐园、灯光、出入口及门口 LED 已同步`);}
for(const preset of COUNTRY_PRESETS){const b=document.createElement('button');b.type='button';b.dataset.country=preset.id;b.textContent=preset.label;b.style.setProperty('--country-color',preset.color);b.onclick=()=>selectCountry(preset.id);$('#countryButtons').append(b);}
selectCountry(selectedCountry,false);
$('.intro h1').textContent='走进全球展厅';$('#lights').nextElementSibling.textContent='氛围光带';
function fitOverview(position,target){const a=new THREE.Vector3(...position),b=new THREE.Vector3(...target);return a.sub(b).multiplyScalar(Math.max(1,Math.min(2.1,1/camera.aspect))).add(b);}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;renderer.setSize(w,h,false);composer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();controls.maxDistance=45;if(state.mode==='overview'&&state.zone==='all'&&!state.transition){camera.position.copy(fitOverview(ZONES[0].camera,ZONES[0].target));controls.target.set(...ZONES[0].target);}const half=6.3*Math.max(1,1/(w/h));planCamera.left=-half*w/h;planCamera.right=half*w/h;planCamera.top=half;planCamera.bottom=-half;planCamera.updateProjectionMatrix();}
new ResizeObserver(resize).observe(viewport);resize();

// Reusable zone navigation, cards and hotspots are driven by ZONES.
const nav=$('#zoneNav');for(const [i,z]of ZONES.entries()){const b=document.createElement('button');b.dataset.zone=z.id;b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span>${z.name}<span class="arrow">↗</span>`;b.onclick=()=>selectZone(z.id);nav.append(b);}
const hotspotEls=[];for(const [i,z]of ZONES.entries()){if(!z.point)continue;const button=document.createElement('button');button.className='hotspot';button.innerHTML=`<b>${String(i).padStart(2,'0')}</b>${z.short}`;button.title=z.name;button.onclick=()=>selectZone(z.id);$('#hotspots').append(button);hotspotEls.push({el:button,point:new THREE.Vector3(...world(z.point,z.id==='party'?1.55:1.7))});}
function transition(position,target,duration=1400){if(state.mode==='walk')setMode('overview',false);activeCamera=camera;camera.fov=state.mode==='entry'?58:43;camera.updateProjectionMatrix();controls.object=camera;controls.enabled=true;renderPass.camera=camera;const destination=state.mode==='overview'&&state.zone==='all'?fitOverview(position,target):new THREE.Vector3(...position);state.transition={from:camera.position.clone(),to:destination,fromTarget:controls.target.clone(),toTarget:new THREE.Vector3(...target),start:performance.now(),duration:reduced?1:duration};}
function selectionUI(){for(const b of $$('[data-zone]')){b.classList.toggle('selected',b.dataset.zone===state.zone);b.setAttribute('aria-pressed',String(b.dataset.zone===state.zone));}for(const b of $$('[data-view]')){b.classList.toggle('selected',b.dataset.view===state.mode);b.setAttribute('aria-pressed',String(b.dataset.view===state.mode));}}
const ZONE_SHOTS={ticket:{eye:[100,690],height:4.2},cafe:{eye:[329,513],height:3.1},party:{eye:[355,348],height:3.1},gaming:{eye:[364,406],height:3.0},prepare:{eye:[502,345],height:2.9},gates:{eye:[510,555],height:3.0}};
function selectZone(id){endTour(false);state.zone=id;const z=ZONES.find(z=>z.id===id);$('#detailTag').textContent=z.tag;$('#detailTitle').textContent=z.title;$('#detailText').textContent=z.description;$('#visitBtn').innerHTML=id==='all'?'从入口开始参观 <span>→</span>':'在这里漫游 <span>→</span>';state.mode='overview';controls.enableRotate=true;controls.mouseButtons.LEFT=THREE.MOUSE.ROTATE;if(id==='all')transition(z.camera,z.target);else{const target=world(z.point,1);const shot=ZONE_SHOTS[id];transition(world(shot.eye,shot.height),target);}$('#cameraLabel').textContent=z.name;$('#cameraHelp').textContent='拖拽旋转 · 滚轮缩放 · 右键平移';$('#walkPad').hidden=true;selectionUI();}
function setMode(mode,move=true){state.transition=null;state.mode=mode;$('#walkPad').hidden=mode!=='walk';controls.enabled=mode!=='walk';activeCamera=mode==='plan'?planCamera:camera;controls.object=activeCamera;renderPass.camera=activeCamera;const hints={overview:['全景鸟瞰','拖拽旋转 · 滚轮缩放 · 右键平移'],plan:['俯视平面','与原图共用坐标 · 滚轮缩放 · 拖拽平移'],entry:['从入口看展厅','拖拽查看吧台、吊顶与门头'],walk:['自由漫游','W A S D 移动 · 拖拽转向 · Esc 返回鸟瞰']};$('#cameraLabel').textContent=hints[mode][0];$('#cameraHelp').textContent=hints[mode][1];
 controls.enableRotate=mode!=='plan';controls.mouseButtons.LEFT=mode==='plan'?THREE.MOUSE.PAN:THREE.MOUSE.ROTATE;
 if(mode==='plan'){planCamera.position.set(0,25,.001);planCamera.zoom=1;planCamera.updateProjectionMatrix();controls.target.set(0,0,0);controls.update();model.shell.visible=false;}
 else{model.shell.visible=!$('#cutaway').checked;if(mode==='walk'){const z=ZONES.find(z=>z.id===state.zone);const p=z?.viewPoint||[169,774],target=z?.point||[245,594];camera.position.set(...world(p,1.65));const t=new THREE.Vector3(...world(target,1.65));const d=t.sub(camera.position);state.yaw=Math.atan2(-d.x,-d.z);state.pitch=0;setWalkLook();}
 else if(move){if(mode==='entry')transition(world([166,847],1.72),world([339,371],1.5),1600);else transition(ZONES[0].camera,ZONES[0].target);}}
 selectionUI();}
for(const b of $$('[data-view]'))b.onclick=()=>{endTour(false);setMode(b.dataset.view);};$('#resetBtn').onclick=()=>{selectZone('all');setMode('overview');};$('#planBtn').onclick=()=>{endTour(false);setMode('plan');};
$('#visitBtn').onclick=()=>{if(state.zone==='all')startTour('entry');else setMode('walk');};
$('#cutaway').onchange=()=>{model.shell.visible=state.mode!=='plan'&&!$('#cutaway').checked;renderer.shadowMap.needsUpdate=true;};
$('#labels').onchange=()=>$('#hotspots').hidden=!$('#labels').checked;$('#people').onchange=()=>model.people.visible=$('#people').checked;
$('#lights').onchange=()=>{const enabled=$('#lights').checked;model.lightGroup.visible=enabled;model.lights.forEach(l=>l.visible=enabled);bloom.strength=enabled?.4:.05;};
$('#referenceBtn').onclick=()=>$('#referenceDialog').showModal();$('#helpBtn').onclick=()=>$('#helpDialog').showModal();for(const b of $$('[data-close]'))b.onclick=()=>$('#'+b.dataset.close).close();for(const d of $$('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
$('#fullscreen').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();}catch{toast('当前窗口不支持全屏，可扩大浏览器窗口查看。');}};document.addEventListener('fullscreenchange',()=>$('#fullscreen').textContent=document.fullscreenElement?'退出全屏':'全屏');

function startTour(id){state.route=id;state.stop=0;model.setRoute(id);$('#tourCard').hidden=false;$('#stopTour').hidden=false;for(const b of $$('[data-route]'))b.classList.toggle('selected',b.dataset.route===id);showStop();}
function showStop(){const r=ROUTES[state.route],s=r.stops[state.stop];state.mode='entry';$('#walkPad').hidden=true;controls.enabled=true;controls.enableRotate=true;controls.mouseButtons.LEFT=THREE.MOUSE.ROTATE;$('#tourCount').textContent=`${r.name}　${state.stop+1} / ${r.stops.length}`;$('#tourTitle').textContent=s.title;$('#tourText').textContent=s.text;$('#prevStop').disabled=state.stop===0;$('#nextStop').textContent=state.stop===r.stops.length-1?'完成体验':'下一步 →';$('#cameraLabel').textContent=s.title;$('#cameraHelp').textContent='按步骤体验现场流程，随时结束返回自由查看';transition(world(s.at,1.9),world(s.look,1.2),1700);selectionUI();}
function endTour(notify=true){state.route=null;model.setRoute(null);$('#tourCard').hidden=true;$('#stopTour').hidden=true;$$('[data-route]').forEach(b=>b.classList.remove('selected'));if(notify){selectZone('all');toast('已返回展厅总览');}}
for(const b of $$('[data-route]'))b.onclick=()=>startTour(b.dataset.route);$('#stopTour').onclick=()=>endTour();$('#prevStop').onclick=()=>{if(state.stop>0){state.stop--;showStop();}};$('#nextStop').onclick=()=>{if(state.stop<ROUTES[state.route].stops.length-1){state.stop++;showStop();}else endTour();};

// Walking uses fixed eye height and furniture / partition collision checks.
function inPolygon(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(((a[1]>p[1])!==(b[1]>p[1]))&&(p[0]<(b[0]-a[0])*(p[1]-a[1])/(b[1]-a[1])+a[0]))inside=!inside;}return inside;}
function pointToSource(v){return [v.x/PLAN.scale+350,v.z/PLAN.scale+430];}
const counterPolys=model.solids.filter(o=>o.type==='shape').map(o=>o.shape.getPoints(90).map(p=>[p.x,-p.y]));
function canWalk(v,previous){if(v.x< -5.15||v.x>10.1||v.z< -5.43||v.z>7.4)return false;const p=pointToSource(v),old=pointToSource(previous);for(const poly of counterPolys)if(inPolygon([v.x,v.z],poly))return false;
 for(const s of model.solids){if(s.type==='circle'&&Math.hypot((p[0]-s.p[0])*PLAN.scale,(p[1]-s.p[1])*PLAN.scale)<s.r+.12)return false;if(s.type==='rect'&&Math.abs(v.x-s.x)<s.w/2+.1&&Math.abs(v.z-s.z)<s.d/2+.1)return false;}
 if(inPolygon(p,PLAN.party)!==inPolygon(old,PLAN.party)){if(Math.hypot(p[0]-236,p[1]-316)>31)return false;}
 if((old[1]<746)!==(p[1]<746)){if(!((p[0]>65&&p[0]<236)||(p[0]>500&&p[0]<641)))return false;}
 if(p[0]<145&&p[1]<322)return false;return true;}
function setWalkLook(){camera.fov=62;camera.updateProjectionMatrix();camera.rotation.order='YXZ';camera.rotation.set(state.pitch,state.yaw,0);}
canvas.addEventListener('pointerdown',e=>{if(state.mode!=='walk')return;state.drag=true;state.lastPointer=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!state.drag||state.mode!=='walk')return;state.yaw-=(e.clientX-state.lastPointer[0])*.004;state.pitch=THREE.MathUtils.clamp(state.pitch-(e.clientY-state.lastPointer[1])*.003,-.7,.65);state.lastPointer=[e.clientX,e.clientY];setWalkLook();});for(const evt of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(evt,()=>state.drag=false);
window.addEventListener('keydown',e=>{if($$('dialog[open]').length)return;if(e.code==='Escape'&&state.mode==='walk'){setMode('overview');return;}if(state.mode==='walk'&&['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){state.keys.add(e.code);e.preventDefault();}});window.addEventListener('keyup',e=>state.keys.delete(e.code));window.addEventListener('blur',()=>state.keys.clear());
const moveCodes={forward:'KeyW',left:'KeyA',back:'KeyS',right:'KeyD'};for(const b of $$('[data-move]')){b.addEventListener('pointerdown',e=>{state.keys.add(moveCodes[b.dataset.move]);b.setPointerCapture(e.pointerId);});for(const evt of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(evt,()=>state.keys.delete(moveCodes[b.dataset.move]));}
function updateWalk(dt){const keys=state.keys,forward=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0),right=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0);if(!forward&&!right)return;const step=new THREE.Vector3(-Math.sin(state.yaw)*forward+Math.cos(state.yaw)*right,0,-Math.cos(state.yaw)*forward-Math.sin(state.yaw)*right).normalize().multiplyScalar(dt*1.7);const next=camera.position.clone().add(step);if(canWalk(next,camera.position))camera.position.copy(next);else{const a=camera.position.clone();a.x+=step.x;if(canWalk(a,camera.position))camera.position.copy(a);const b=camera.position.clone();b.z+=step.z;if(canWalk(b,camera.position))camera.position.copy(b);}camera.position.y=1.65;}

const map=$('#map'),ctx=map.getContext('2d');function drawMap(){const scale=.44,offset=[-7,-21];ctx.clearRect(0,0,map.width,map.height);ctx.save();ctx.translate(...offset);ctx.scale(scale,scale);function polygon(ps,fill,stroke){ctx.beginPath();ps.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.stroke();}polygon(PLAN.boundary,'#132e42','#4b7b9d');polygon(PLAN.party,'#2a3650','#799bb5');for(const sh of [model.cafeShape,model.ticketShape]){const pts=sh.getPoints(60).map(p=>[p.x/PLAN.scale+350,-p.y/PLAN.scale+430]);polygon(pts,'#88afc8','#ace0fa');}for(const p of [[465,273],[511,273]]){ctx.fillStyle='#446c8e';ctx.fillRect(p[0]-17,p[1]-26,34,52);}for(const y of [385,420,456,647,683,718]){ctx.fillStyle='#3280b6';ctx.fillRect(618,y-6,64,12);}ctx.strokeStyle='#f1c867';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(55,750);ctx.lineTo(244,750);ctx.stroke();ctx.strokeStyle='#4081cd';ctx.beginPath();ctx.moveTo(277,750);ctx.lineTo(476,750);ctx.stroke();ctx.strokeStyle='#63c5b0';ctx.beginPath();ctx.moveTo(494,750);ctx.lineTo(650,750);ctx.stroke();if(state.route){ctx.strokeStyle='#'+ROUTES[state.route].color.toString(16);ctx.lineWidth=5;ctx.beginPath();ROUTES[state.route].path.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}const p=pointToSource(activeCamera.position);if(state.mode==='walk'||state.mode==='entry'){ctx.fillStyle='#f5fbff';ctx.beginPath();ctx.arc(p[0],p[1],9,0,7);ctx.fill();const dir=new THREE.Vector3();activeCamera.getWorldDirection(dir);ctx.strokeStyle='#9ae7ff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(...p);ctx.lineTo(p[0]+dir.x*45,p[1]+dir.z*45);ctx.stroke();}ctx.restore();}
map.addEventListener('click',()=>setMode('plan'));
function updateLabels(){const width=viewport.clientWidth,height=viewport.clientHeight;for(const h of hotspotEls){const p=h.point.clone().project(activeCamera);const visible=p.z<1&&p.z> -1&&p.x>-.98&&p.x<.98&&p.y>-.92&&p.y<.93&&state.mode!=='walk';h.el.style.display=visible?'':'none';h.el.style.left=`${(p.x*.5+.5)*width}px`;h.el.style.top=`${(-p.y*.5+.5)*height}px`;}}
let last=performance.now(),frames=0;const frameSamples=[];function animate(now){requestAnimationFrame(animate);const elapsed=now-last,dt=Math.min(.05,elapsed/1000);last=now;if(document.hidden)return;if(frames>10&&elapsed<250){frameSamples.push(elapsed);if(frameSamples.length>90)frameSamples.shift();}
 if(state.transition){const tr=state.transition,raw=Math.min(1,(now-tr.start)/tr.duration),t=raw<.5?4*raw**3:1-(-2*raw+2)**3/2;camera.position.lerpVectors(tr.from,tr.to,t);controls.target.lerpVectors(tr.fromTarget,tr.toTarget,t);if(raw===1)state.transition=null;}
 if(state.mode==='walk')updateWalk(dt);else controls.update();model.update(reduced?0:now/1000,activeCamera);if(frames++%3===0){drawMap();updateLabels();}renderer.info.reset();composer.render();if(frames===3)loading.classList.add('loaded');if(frames===120){const i=renderer.info;console.info('SHOWROOM_RENDER',JSON.stringify({calls:i.render.calls,triangles:i.render.triangles,geometries:i.memory.geometries,textures:i.memory.textures,dpr:QUALITY.dpr,reflection:QUALITY.reflectionSize,frameMs:Math.round(frameSamples.reduce((a,b)=>a+b,0)/frameSamples.length*10)/10,counterHeight:PLAN.counterHeight,pendant:PLAN.pendantUnderside}));}}
requestAnimationFrame(animate);selectionUI();
window.__showroom={state,model,camera,planCamera,renderer,controls,selectZone,setMode,startTour,endTour,getInfo:()=>({mode:state.mode,zone:state.zone,route:state.route,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,counterHeight:PLAN.counterHeight,pendantUnderside:PLAN.pendantUnderside,source:PLAN.image})};
window.addEventListener('error',()=>toast('场景遇到加载问题，请刷新页面重试。'));
